version: "3"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - "../telemed_scheduler_api_db:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "15672:15672"


  redis:
    image: redis:6
    ports:
      - "6379:6379"
    command: redis-server --requirepass pass

  docker-hoster:
    image: dvdarias/docker-hoster
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "/etc/hosts:/tmp/hosts"
